version: '3.8'

services:
  web:
  # REQUIRES: ./php folder for hosting the PHP files
  # REQUIRES: port 8888 on the host machine to be open, so browsing to http://localhost:8080/query.php will run the queries
    # image: php:7.4-apache
    build: ./php
    container_name: php_web
    volumes:
      - ./php:/var/www/html
    ports:
      - "8888:80"
    depends_on:
      - db
    networks:
      - app-network

  # the service name is defined here as "db" this is the "hostname" within docker for the mysql server.
  db:
  # REQUIRES: ./mysql folder for storing the init.sql file which creates the initial tables in the db
    image: lscr.io/linuxserver/mariadb:10.11.5
    # technically it's running mariadb under the hood now as that was easier to setup poorly. lol
    # to solve the error: "no matching manifest for linux/arm64/v8 in the manifest list entries"
    #platform: linux/amd64
    container_name: mysql_db
    volumes:
      - db_data:/config
      - ./php:/var/www/html
      - ./mysql/init.sql:/config/initdb.d/init.sql
    environment:
    # NOTE: mysql root password isn't really needed unless logging into the mysql CLI console.
      MYSQL_ROOT_PASSWORD: iamrootpassword
      MYSQL_DATABASE: sqli_database
      # if you aren't logged in as UID 1000 or GID 1000, then this will need your attention.
      # I'm too lazy to run this dynamically to fix that issue. GL!
      PUID: 1000
      PGID: 1000
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
